var hash2 = {"0" :["A1", "Anonymous Proxy"],
"1" :["A2", "Satellite Provider"],
"2" :["AD", "Andorra"],
"3" :["AE", "United Arab Emirates"],
"4" :["AF", "Afghanistan"],
"5" :["AG", "Antigua and Barbuda"],
"6" :["AI", "Anguilla"],
"7" :["AL", "Albania"],
"8" :["AM", "Armenia"],
"9" :["AO", "Angola"],
"10" :["AP", "Asia/Pacific Region"],
"11" :["AQ", "Antarctica"],
"12" :["AR", "Argentina"],
"13" :["AS", "American Samoa"],
"14" :["AT", "Austria"],
"15" :["AU", "Australia"],
"16" :["AW", "Aruba"],
"17" :["AX", "Aland Islands"],
"18" :["AZ", "Azerbaijan"],
"19" :["BA", "Bosnia and Herzegovina"],
"20" :["BB", "Barbados"],
"21" :["BD", "Bangladesh"],
"22" :["BE", "Belgium"],
"23" :["BF", "Burkina Faso"],
"24" :["BG", "Bulgaria"],
"25" :["BH", "Bahrain"],
"26" :["BI", "Burundi"],
"27" :["BJ", "Benin"],
"28" :["BL", "Saint Barthelemy"],
"29" :["BM", "Bermuda"],
"30" :["BN", "Brunei Darussalam"],
"31" :["BO", "Bolivia"],
"32" :["BQ", "Bonaire" :[" Saint Eustatius and Saba"],
"33" :["BR", "Brazil"],
"34" :["BS", "Bahamas"],
"35" :["BT", "Bhutan"],
"36" :["BW", "Botswana"],
"37" :["BY", "Belarus"],
"38" :["BZ", "Belize"],
"39" :["CA", "Canada"],
"40" :["CC", "Cocos (Keeling) Islands"],
"41" :["CD", "Congo" :[" The Democratic Republic of the"],
"42" :["CF", "Central African Republic"],
"43" :["CG", "Congo"],
"44" :["CH", "Switzerland"],
"45" :["CI", "Cote D'Ivoire"],
"46" :["CK", "Cook Islands"],
"47" :["CL", "Chile"],
"48" :["CM", "Cameroon"],
"49" :["CN", "China"],
"50" :["CO", "Colombia"],
"51" :["CR", "Costa Rica"],
"52" :["CU", "Cuba"],
"53" :["CV", "Cape Verde"],
"54" :["CW", "Curacao"],
"55" :["CX", "Christmas Island"],
"56" :["CY", "Cyprus"],
"57" :["CZ", "Czech Republic"],
"58" :["DE", "Germany"],
"59" :["DJ", "Djibouti"],
"60" :["DK", "Denmark"],
"61" :["DM", "Dominica"],
"62" :["DO", "Dominican Republic"],
"63" :["DZ", "Algeria"],
"64" :["EC", "Ecuador"],
"65" :["EE", "Estonia"],
"66" :["EG", "Egypt"],
"67" :["ER", "Eritrea"],
"68" :["ES", "Spain"],
"69" :["ET", "Ethiopia"],
"70" :["EU", "Europe"],
"71" :["FI", "Finland"],
"72" :["FJ", "Fiji"],
"73" :["FK", "Falkland Islands (Malvinas)"],
"74" :["FM", "Micronesia" :[" Federated States of"],
"75" :["FO", "Faroe Islands"],
"76" :["FR", "France"],
"77" :["GA", "Gabon"],
"78" :["GB", "United Kingdom"],
"79" :["GD", "Grenada"],
"80" :["GE", "Georgia"],
"81" :["GF", "French Guiana"],
"82" :["GG", "Guernsey"],
"83" :["GH", "Ghana"],
"84" :["GI", "Gibraltar"],
"85" :["GL", "Greenland"],
"86" :["GM", "Gambia"],
"87" :["GN", "Guinea"],
"88" :["GP", "Guadeloupe"],
"89" :["GQ", "Equatorial Guinea"],
"90" :["GR", "Greece"],
"91" :["GS", "South Georgia and the South Sandwich Islands"],
"92" :["GT", "Guatemala"],
"93" :["GU", "Guam"],
"94" :["GW", "Guinea-Bissau"],
"95" :["GY", "Guyana"],
"96" :["HK", "Hong Kong"],
"97" :["HN", "Honduras"],
"98" :["HR", "Croatia"],
"99" :["HT", "Haiti"],
"100" :["HU", "Hungary"],
"101" :["ID", "Indonesia"],
"102" :["IE", "Ireland"],
"103" :["IL", "Israel"],
"104" :["IM", "Isle of Man"],
"105" :["IN", "India"],
"106" :["IO", "British Indian Ocean Territory"],
"107" :["IQ", "Iraq"],
"108" :["IR", "Iran" :[" Islamic Republic of"],
"109" :["IS", "Iceland"],
"110" :["IT", "Italy"],
"111" :["JE", "Jersey"],
"112" :["JM", "Jamaica"],
"113" :["JO", "Jordan"],
"114" :["JP", "Japan"],
"115" :["KE", "Kenya"],
"116" :["KG", "Kyrgyzstan"],
"117" :["KH", "Cambodia"],
"118" :["KI", "Kiribati"],
"119" :["KM", "Comoros"],
"120" :["KN", "Saint Kitts and Nevis"],
"121" :["KP", "Korea" :[" Democratic People's Republic of"],
"122" :["KR", "Korea" :[" Republic of"],
"123" :["KW", "Kuwait"],
"124" :["KY", "Cayman Islands"],
"125" :["KZ", "Kazakhstan"],
"126" :["LA", "Lao People's Democratic Republic"],
"127" :["LB", "Lebanon"],
"128" :["LC", "Saint Lucia"],
"129" :["LI", "Liechtenstein"],
"130" :["LK", "Sri Lanka"],
"131" :["LR", "Liberia"],
"132" :["LS", "Lesotho"],
"133" :["LT", "Lithuania"],
"134" :["LU", "Luxembourg"],
"135" :["LV", "Latvia"],
"136" :["LY", "Libya"],
"137" :["MA", "Morocco"],
"138" :["MC", "Monaco"],
"139" :["MD", "Moldova" :[" Republic of"],
"140" :["ME", "Montenegro"],
"141" :["MF", "Saint Martin"],
"142" :["MG", "Madagascar"],
"143" :["MH", "Marshall Islands"],
"144" :["MK", "Macedonia"],
"145" :["ML", "Mali"],
"146" :["MM", "Myanmar"],
"147" :["MN", "Mongolia"],
"148" :["MO", "Macau"],
"149" :["MP", "Northern Mariana Islands"],
"150" :["MQ", "Martinique"],
"151" :["MR", "Mauritania"],
"152" :["MS", "Montserrat"],
"153" :["MT", "Malta"],
"154" :["MU", "Mauritius"],
"155" :["MV", "Maldives"],
"156" :["MW", "Malawi"],
"157" :["MX", "Mexico"],
"158" :["MY", "Malaysia"],
"159" :["MZ", "Mozambique"],
"160" :["NA", "Namibia"],
"161" :["NC", "New Caledonia"],
"162" :["NE", "Niger"],
"163" :["NF", "Norfolk Island"],
"164" :["NG", "Nigeria"],
"165" :["NI", "Nicaragua"],
"166" :["NL", "Netherlands"],
"167" :["NO", "Norway"],
"168" :["NP", "Nepal"],
"169" :["NR", "Nauru"],
"170" :["NU", "Niue"],
"171" :["NZ", "New Zealand"],
"172" :["OM", "Oman"],
"173" :["PA", "Panama"],
"174" :["PE", "Peru"],
"175" :["PF", "French Polynesia"],
"176" :["PG", "Papua New Guinea"],
"177" :["PH", "Philippines"],
"178" :["PK", "Pakistan"],
"179" :["PL", "Poland"],
"180" :["PM", "Saint Pierre and Miquelon"],
"181" :["PN", "Pitcairn Islands"],
"182" :["PR", "Puerto Rico"],
"183" :["PS", "Palestinian Territory"],
"184" :["PT", "Portugal"],
"185" :["PW", "Palau"],
"186" :["PY", "Paraguay"],
"187" :["QA", "Qatar"],
"188" :["RE", "Reunion"],
"189" :["RO", "Romania"],
"190" :["RS", "Serbia"],
"191" :["RU", "Russian Federation"],
"192" :["RW", "Rwanda"],
"193" :["SA", "Saudi Arabia"],
"194" :["SB", "Solomon Islands"],
"195" :["SC", "Seychelles"],
"196" :["SD", "Sudan"],
"197" :["SE", "Sweden"],
"198" :["SG", "Singapore"],
"199" :["SH", "Saint Helena"],
"200" :["SI", "Slovenia"],
"201" :["SJ", "Svalbard and Jan Mayen"],
"202" :["SK", "Slovakia"],
"203" :["SL", "Sierra Leone"],
"204" :["SM", "San Marino"],
"205" :["SN", "Senegal"],
"206" :["SO", "Somalia"],
"207" :["SR", "Suriname"],
"208" :["SS", "South Sudan"],
"209" :["ST", "Sao Tome and Principe"],
"210" :["SV", "El Salvador"],
"211" :["SX", "Sint Maarten (Dutch part)"],
"212" :["SY", "Syrian Arab Republic"],
"213" :["SZ", "Swaziland"],
"214" :["TC", "Turks and Caicos Islands"],
"215" :["TD", "Chad"],
"216" :["TF", "French Southern Territories"],
"217" :["TG", "Togo"],
"218" :["TH", "Thailand"],
"219" :["TJ", "Tajikistan"],
"220" :["TK", "Tokelau"],
"221" :["TL", "Timor-Leste"],
"222" :["TM", "Turkmenistan"],
"223" :["TN", "Tunisia"],
"224" :["TO", "Tonga"],
"225" :["TR", "Turkey"],
"226" :["TT", "Trinidad and Tobago"],
"227" :["TV", "Tuvalu"],
"228" :["TW", "Taiwan"],
"229" :["TZ", "Tanzania" :[" United Republic of"],
"230" :["UA", "Ukraine"],
"231" :["UG", "Uganda"],
"232" :["UM", "United States Minor Outlying Islands"],
"233" :["US", "United States"],
"234" :["UY", "Uruguay"],
"235" :["UZ", "Uzbekistan"],
"236" :["VA", "Holy See (Vatican City State)"],
"237" :["VC", "Saint Vincent and the Grenadines"],
"238" :["VE", "Venezuela"],
"239" :["VG", "Virgin Islands" :[" British"],
"240" :["VI", "Virgin Islands" :[" U.S."],
"241" :["VN", "Vietnam"],
"242" :["VU", "Vanuatu"],
"243" :["WF", "Wallis and Futuna"],
"244" :["WS", "Samoa"],
"245" :["YE", "Yemen"],
"246" :["YT", "Mayotte"],
"247" :["ZA", "South Africa"],
"248" :["ZM", "Zambia"],
"249" :["ZW", "Zimbabwe"]
};
